name: Release Docker Image

on:
  workflow_dispatch: # for manual testing
    inputs:
      runs_on:
        type: choice
        description: "Runs on"
        options:
          - self-hosted
          - self-hosted-dind
          - ubuntu-latest
      dind:
        type: boolean
        description: "Docker-in-Docker runner"
        default: false
  push:
    branches:
      - main

jobs:
  call-docker-release:
    permissions:
      contents: read
      packages: write
    uses: thealtoclef/modular-automations/.github/workflows/docker-release.yaml@main
    with:
      runs_on: ${{ github.event.inputs.runs_on || 'self-hosted' }}
      dind: ${{ github.event.inputs.dind == 'true' }}
      is_monorepo: true
